### ISSUE TITLE
Fails to work when GitHub Token is read only

### ISSUE THREAD

**Issue by leosuncin** [tanmen/jest-reporter#8]
The action fails when the github token is read only and throws `Error: HttpError: Resource not accessible by integration` 

This happen due a change in [GitHub Actions: Workflows triggered by Dependabot PRs will run with read-only permissions](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/)

[![Failed run](https://user-images.githubusercontent.com/4307697/115131712-71158780-9fb7-11eb-9f60-d5a5cbb540f7.png)](https://github.com/leosuncin/react-auth-example/runs/2368368645)

**Comment by tanmen** [comment]
Thanks for reporting the issue.
I'll try to deal with it now.

**Comment by tanmen** [comment]
@leosuncin 
It turns out that this problem cannot be solved.
This is due to the fact that we are writing to checks, and we should not include in this action whether we have permission to do so or not.
Since we are now creating actions to get permissions, it seems reasonable to change this action to run only if we have write permission on checks.

**Comment by tanmen** [comment]
I now understand that there is no way to find out the permissions of `GITHUB-TOKEN`.
I also understand that a job can't skip itself when it doesn't have permissions.

Can you please try to work around the current situation in the following way?
```
     - run: yarn test --coverage --json --outputFile=result.json --testLocationInResults
        id: test
        env:
          CI: true
      - uses: tanmen/jest-reporter@v1
        if: failure() && steps.test.outcome == 'failure'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by tanmen** [comment]
I also found it annoying and responded by letting it succeed and skipping it.
If you have any comments, please feel free to create another issue :)))

https://github.com/tanmen/jest-reporter/commit/bff08bbc39ba5d1bb6ac54436fa8558baac18ced

**Comment by leosuncin** [comment]
The action needs the following permissions:

```yaml
permissions:
      contents: read
      checks: write
      pull-requests: write
```

Reference: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

@tanmen, I will open a PR to update the README
